routes:
  '/':
    controller: 'DefaultController'
    function: 'DefaultAction'

  '/post/{id}':
    controller: 'PostController'
    function: 'DefaultAction'

  '/article':
    controller: 'PostController'
    function: 'PostByUserAction'

  '/contact':
    controller: 'ContactController'
    function: 'DefaultAction'

  '/sign':
    controller: 'LoginController'
    function: 'LoginAction'

  '/login':
    controller: 'LoginController'
    function: 'DefaultAction'

  '/updatepost':
    controller: 'PostController'
    function: 'UpdatePost'
    methods:
      - POST

  '/validlogin':
    controller: 'LoginController'
    function: 'ValidLogin'
    methods:
      - POST

  '/saveusers':
    controller: 'UsersController'
    function: 'SaveUsers'
    methods:
      - POST

  '/updateactif':
    controller: 'PostController'
    function: 'UpdateActifByPost'
    methods:
      - POST

  '/suppost':
    controller: 'PostController'
    function: 'SupPostById'
    methods:
      - POST

  '/newpost':
    controller: 'PostController'
    function: 'NewPost'
    methods:
      - POST

  '/uploadfile':
    controller: 'UploadFile'
    function: 'UpdatePost'
    methods:
      - POST

  '/disconnect':
    controller: 'LoginController'
    function: 'DisconnectAction'