routes:
  '/':
    controller: 'DefaultController'
    function: 'DefaultAction'

  '/post/{id}':
    controller: 'PostController'
    function: 'DefaultAction'

  '/article':
    controller: 'PostController'
    function: 'PostByUserAction'

  '/updatepost':
    controller: 'PostController'
    function: 'UpdatePost'
    methods:
      - POST

  '/login':
    controller: 'LoginController'
    function: 'DefaultAction'
    role :
      - ROLE_ADMIN

  '/validlogin':
    controller: 'LoginController'
    function: 'ValidLogin'
    methods:
      - POST

  '/updateactif':
    controller: 'PostController'
    function: 'UpdateActifByPost'
    methods:
      - POST

  '/disconnect':
    controller: 'LoginController'
    function: 'DisconnectAction'