routes:
  '/':
    controller: 'DefaultController'
    function: 'DefaultAction'

  '/post/{id}':
    controller: 'PostController'
    function: 'DefaultAction'

  '/article':
    controller: 'PostController'
    function: 'PostByUserAction'

  '/contact':
    controller: 'ContactController'
    function: 'DefaultAction'

  '/sign':
    controller: 'LoginController'
    function: 'LoginAction'

  '/login':
    controller: 'LoginController'
    function: 'DefaultAction'

  '/gestutil':
    controller: 'UsersController'
    function: 'DefaultAction'
    access:
      - ROLE_ADMIN

  '/gestcom':
    controller: 'ComController'
    function: 'DefaultAction'

  '/updatepost':
    controller: 'PostController'
    function: 'UpdatePost'
    methods:
      - POST

  '/validlogin':
    controller: 'LoginController'
    function: 'ValidLogin'
    methods:
      - POST

  '/saveusers':
    controller: 'UsersController'
    function: 'SaveUsers'
    methods:
      - POST

  '/savecom':
    controller: 'ComController'
    function: 'SaveCom'
    methods:
      - POST

  '/updateactif':
    controller: 'PostController'
    function: 'UpdateActifByPost'
    methods:
      - POST

  '/updatecomsactif':
    controller: 'ComController'
    function: 'UpdateComsActifById'
    methods:
      - POST

  '/updateusersactif':
    controller: 'UsersController'
    function: 'UpdateActifByUser'
    methods:
      - POST

  '/suppost':
    controller: 'PostController'
    function: 'SupPostById'
    methods:
      - POST

  '/supuser':
    controller: 'UsersController'
    function: 'SupUserById'
    methods:
      - POST

  '/supcom':
    controller: 'ComController'
    function: 'SupComById'
    methods:
      - POST

  '/newpost':
    controller: 'PostController'
    function: 'NewPost'
    methods:
      - POST

  '/uploadfile':
    controller: 'UploadFile'
    function: 'UpdatePost'
    methods:
      - POST

  '/disconnect':
    controller: 'LoginController'
    function: 'DisconnectAction'